# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox tox-pyenv tox-travis

# command to run tests, e.g. python setup.py test
script: tox
